/**
 * LEVEL 1: FILE HEADER
 * FILENAME: author.entity.ts
 * PATH: src/authors/entities/author.entity.ts
 * LANGUAGE: TypeScript
 * PARADIGM: Object-Relational Mapping (ORM)
 * PURPOSE: Defines the Author database schema and relationships.
 * DEPENDENCIES: typeorm, ../../books/entities/book.entity, ../../profiles/entities/profile.entity
 * CONTEXT: Used by TypeORM to map class instances to the 'author' table.
 * AUTHOR NOTES: Standard TypeORM entity definition.
 * LAST MODIFIED: 2024-05-22
 */

// ============================================================================
// LEVEL 2: SECTION DIVIDERS - IMPORTS
// ============================================================================

import {
    Column,
    Entity,
    OneToMany,
    OneToOne,
    PrimaryGeneratedColumn,
} from 'typeorm';

import { Book } from '../../books/entities/book.entity';
import { Profile } from '../../profiles/entities/profile.entity';

// ============================================================================
// LEVEL 2: SECTION DIVIDERS - ENTITY DEFINITION
// ============================================================================

/**
 * LEVEL 3: CLASS DOCUMENTATION
 * CLASS: Author
 * VISIBILITY: Exported
 * WHAT: Represents the 'author' table in the database.
 * HOW: Annotated with @Entity() for TypeORM recognition and mapping.
 * RELATIONSHIPS: 
 *   - OneToOne with Profile: An author has exactly one profile.
 *   - OneToMany with Book: An author can write multiple books.
 */
@Entity()
export class Author {
    /**
     * LEVEL 3: PROPERTY DOCUMENTATION
     * PROPERTY: id
     * WHAT: Primary key for the author record.
     * HOW: Auto-incremented integer generated by the database.
     * FRAMEWORK: @PrimaryGeneratedColumn() handles ID generation logic.
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * LEVEL 3: PROPERTY DOCUMENTATION
     * PROPERTY: name
     * WHAT: Name of the author.
     * HOW: Mapped to a standard VARCHAR column.
     * FRAMEWORK: @Column() defines a basic table column.
     */
    @Column()
    name: string;

    /**
     * LEVEL 3: PROPERTY DOCUMENTATION
     * PROPERTY: email
     * WHAT: Email address of the author.
     * HOW: Mapped to a standard VARCHAR column.
     * FRAMEWORK: @Column() defines a basic table column.
     */
    @Column()
    email: string;

    /**
     * LEVEL 3: RELATIONSHIP DOCUMENTATION
     * RELATION: profile
     * TYPE: One-to-One
     * TARGET: Profile entity
     * WHAT: Linked profile information for this author.
     * WHY: To separate basic author identity from more detailed personal information.
     * HOW: Maps the inverse side of the relationship in the Profile entity.
     * FRAMEWORK: @OneToOne() decorator defines the association.
     */
    @OneToOne(() => Profile, (profile) => profile.author)
    profile: Profile;

    /**
     * LEVEL 3: RELATIONSHIP DOCUMENTATION
     * RELATION: books
     * TYPE: One-to-Many
     * TARGET: Book entity
     * WHAT: List of books authored by this person.
     * WHY: To maintain a collection of all literary works associated with this author.
     * HOW: Maps to the 'author' field in the Book entity.
     * FRAMEWORK: @OneToMany() decorator defines the collection side of the association.
     */
    @OneToMany(() => Book, (book) => book.author)
    books: Book[];
}
