/**
 * LEVEL 1: FILE HEADER
 * FILENAME: book.entity.ts
 * PATH: src/books/entities/book.entity.ts
 * LANGUAGE: TypeScript
 * PARADIGM: Object-Relational Mapping (ORM)
 * PURPOSE: Defines the Book database schema and relationships.
 * DEPENDENCIES: typeorm, ../../authors/entities/author.entity, ../../tags/entities/tag.entity
 * CONTEXT: Used by TypeORM to map class instances to the 'book' table.
 * AUTHOR NOTES: Standard TypeORM entity definition with Many-to-One and Many-to-Many relationships.
 * LAST MODIFIED: 2024-05-22
 */

// ============================================================================
// LEVEL 2: SECTION DIVIDERS - IMPORTS
// ============================================================================

import {
    Column,
    Entity,
    JoinTable,
    ManyToMany,
    ManyToOne,
    PrimaryGeneratedColumn,
} from 'typeorm'

import { Author } from '../../authors/entities/author.entity';
import { Tag } from '../../tags/entities/tag.entity';

// ============================================================================
// LEVEL 2: SECTION DIVIDERS - ENTITY DEFINITION
// ============================================================================

/**
 * LEVEL 3: CLASS DOCUMENTATION
 * CLASS: Book
 * VISIBILITY: Exported
 * WHAT: Represents the 'book' table in the database.
 * HOW: Annotated with @Entity() for TypeORM recognition and mapping.
 * RELATIONSHIPS:
 *   - ManyToOne with Author: Many books can be authored by one person.
 *   - ManyToMany with Tag: Many books can be categorized by many different tags.
 * FRAMEWORK: TypeORM handles the mapping between this class and the SQL table.
 */
@Entity()
export class Book {
    /**
     * LEVEL 3: PROPERTY DOCUMENTATION
     * PROPERTY: id
     * WHAT: Primary key for the book record.
     * HOW: Auto-incremented integer generated by the database.
     * FRAMEWORK: @PrimaryGeneratedColumn() automates ID generation.
     */
    @PrimaryGeneratedColumn()
    id!: number;

    /**
     * LEVEL 3: PROPERTY DOCUMENTATION
     * PROPERTY: title
     * WHAT: The title of the literary work.
     * HOW: Mapped to a standard VARCHAR column in the database.
     * FRAMEWORK: @Column() defines a basic persistent field.
     */
    @Column()
    title!: string;

    /**
     * LEVEL 3: PROPERTY DOCUMENTATION
     * PROPERTY: releaseYear
     * WHAT: The calendar year the book was published.
     * HOW: Mapped to an INTEGER column in the database.
     * FRAMEWORK: @Column() defines a basic persistent field.
     */
    @Column()
    releaseYear!: number;

    /**
     * LEVEL 3: RELATIONSHIP DOCUMENTATION
     * RELATION: author
     * TYPE: Many-to-One
     * TARGET: Author entity
     * WHAT: The single author associated with this book.
     * WHY: To establish a clear link between a work and its creator.
     * HOW: Defined as a foreign key column in the 'book' table.
     * FRAMEWORK: @ManyToOne() decorator links this field to the Author entity.
     */
    @ManyToOne(() => Author, (author) => author.books)
    author!: Author;

    /**
     * LEVEL 3: RELATIONSHIP DOCUMENTATION
     * RELATION: tags
     * TYPE: Many-to-Many
     * TARGET: Tag entity
     * WHAT: A collection of labels applied to this book for categorization.
     * WHY: To allow complex filtering and search across multiple genres or themes.
     * HOW: Managed through an automatically generated join table.
     * FRAMEWORK: @ManyToMany() with @JoinTable() creates the necessary intersection table.
     * SIDE EFFECTS: cascade: true means related Tag operations can be triggered by Book operations.
     */
    @ManyToMany(() => Tag, (tag) => tag.books, {
        cascade: true,
    })
    @JoinTable()
    tags!: Tag[];
}
