/**
 * LEVEL 1: FILE HEADER
 * FILENAME: profile.entity.ts
 * PATH: src/profiles/entities/profile.entity.ts
 * LANGUAGE: TypeScript
 * PARADIGM: Object-Relational Mapping (ORM)
 * PURPOSE: Defines the Profile database schema and its relationship to authors.
 * DEPENDENCIES: typeorm, ../../authors/entities/author.entity
 * CONTEXT: Used by TypeORM to map class instances to the 'profile' table in the Bookstore API.
 * AUTHOR NOTES: Implements a One-to-One relationship where the Profile owns the foreign key.
 * LAST MODIFIED: 2024-05-22
 */

// ============================================================================
// LEVEL 2: SECTION DIVIDERS - IMPORTS
// ============================================================================

import {
  Column,
  Entity,
  JoinColumn,
  OneToOne,
  PrimaryGeneratedColumn
} from 'typeorm';

import { Author } from '../../authors/entities/author.entity';

// ============================================================================
// LEVEL 2: SECTION DIVIDERS - ENTITY DEFINITION
// ============================================================================

/**
 * LEVEL 3: CLASS DOCUMENTATION
 * CLASS: Profile
 * VISIBILITY: Exported
 * WHAT: Represents the 'profile' table in the database, containing extended author details.
 * HOW: Annotated with @Entity() for TypeORM recognition and schema generation.
 * RELATIONSHIPS:
 *   - OneToOne with Author: Each author has exactly one profile.
 * FRAMEWORK: TypeORM handles the mapping between this class and the SQL table.
 */
@Entity()
export class Profile {
  /**
   * LEVEL 3: PROPERTY DOCUMENTATION
   * PROPERTY: id
   * WHAT: Primary key for the profile record.
   * HOW: Auto-incremented integer generated by the database.
   * FRAMEWORK: @PrimaryGeneratedColumn() automates ID generation logic.
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * LEVEL 3: PROPERTY DOCUMENTATION
   * PROPERTY: biography
   * WHAT: Descriptive text about the author's life and career.
   * HOW: Mapped to a standard VARCHAR column in the database.
   * FRAMEWORK: @Column() defines a basic persistent field.
   */
  @Column()
  biography: string;

  /**
   * LEVEL 3: PROPERTY DOCUMENTATION
   * PROPERTY: website
   * WHAT: The URL for the author's personal or professional website.
   * HOW: Mapped to a standard VARCHAR column in the database.
   * FRAMEWORK: @Column() defines a basic persistent field.
   */
  @Column()
  website: string;

  /**
   * LEVEL 3: RELATIONSHIP DOCUMENTATION
   * RELATION: author
   * TYPE: One-to-One
   * TARGET: Author entity
   * WHAT: The specific author to whom this profile belongs.
   * WHY: To link detailed biographical data back to a unique author record.
   * HOW: Uses @JoinColumn() on this side to specify that 'profile' table holds the 'authorId' foreign key.
   * FRAMEWORK: @OneToOne() and @JoinColumn() decorators define the association and its ownership.
   */
  @OneToOne(() => Author, (author) => author.profile)
  @JoinColumn()
  author: Author;
}
